# Generated by Django 4.1.4 on 2023-01-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_upcomingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
