# Generated by Django 4.1.4 on 2023-01-05 00:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_upcomingevent_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
