# Generated by Django 4.1.4 on 2023-01-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_upcomingevent_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingevent',
            options={'ordering': ('-date_posted',)},
        ),
        migrations.AddField(
            model_name='upcomingevent',
            name='eventpast',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
